#!/usr/bin/env Rscript
# =============================================================================
# C01a_diag_profiles.R — Profile plots along chromosome (plots 01-05, 12, 24, 25)
# X-axis = genomic position, Y = metric. One track per chromosome.
# Usage: Rscript C01a_diag_profiles.R <precomp_dir> <outdir> [chrom]
# =============================================================================

SCRIPT_DIR <- dirname(sys.frame(1)$ofile %||% ".")
source(file.path(SCRIPT_DIR, "C01a_diag_common.R"))

cli <- parse_diag_args()
data <- load_diag_data(cli$precomp_dir, cli$chrom_filter)
precomp_list <- data$precomp_list
chroms <- data$chroms
inv_like_dt <- data$inv_like_dt
dir.create(cli$outdir, recursive = TRUE, showWarnings = FALSE)

# =============================================================================
# PROFILE BUILDERS
# =============================================================================

# -- 01: Eigenvalue spectrum ------------------------------------------
build_eigen_profile <- function(chr) {
  dt <- precomp_list[[chr]]$dt
  # Column names: lam_1/lam_2 from STEP10_v2, or lambda1/lambda2
  l1_col <- if ("lam_1" %in% names(dt)) "lam_1" else if ("lambda1" %in% names(dt)) "lambda1" else NULL
  l2_col <- if ("lam_2" %in% names(dt)) "lam_2" else if ("lambda2" %in% names(dt)) "lambda2" else NULL
  if (is.null(l1_col) || is.null(l2_col)) return(NULL)

  pdt <- data.table(
    pos_mb = (dt$start_bp + dt$end_bp) / 2e6,
    lambda1 = dt[[l1_col]],
    lambda2 = dt[[l2_col]]
  )
  pdt[, pve1 := lambda1 / (lambda1 + lambda2)]
  pdt <- pdt[is.finite(lambda1) & is.finite(lambda2) & lambda1 > 0]
  if (nrow(pdt) < 10) return(NULL)

  lam_max <- max(pdt$lambda1, na.rm = TRUE)
  if (!is.finite(lam_max) || lam_max == 0) lam_max <- 1

  p <- ggplot(pdt) +
    geom_line(aes(x = pos_mb, y = lambda1), color = "blue4", linewidth = 0.3, alpha = 0.7) +
    geom_line(aes(x = pos_mb, y = lambda2), color = "red3", linewidth = 0.3, alpha = 0.5) +
    geom_line(aes(x = pos_mb, y = pve1 * lam_max),
              color = "green4", linewidth = 0.4, alpha = 0.6) +
    scale_y_continuous(sec.axis = sec_axis(~ . / lam_max, name = "PVE1 (green)")) +
    labs(x = paste0(chr, " (Mb)"), y = "Eigenvalue",
         title = paste0(chr, " -- Eigenvalue Spectrum"),
         subtitle = paste0("Blue: lambda1, Red: lambda2, Green: PVE1\n",
                          nrow(pdt), " windows"),
         caption = paste0("Median PVE1: ", round(median(pdt$pve1, na.rm = TRUE), 3),
                         " | lambda1/lambda2 median: ",
                         round(median(pdt$lambda1/pdt$lambda2, na.rm = TRUE), 2))) +
    THEME_BASE
  p
}

# -- 02: Inv-likeness profile ----------------------------------------
build_inv_likeness_profile <- function(chr) {
  if (nrow(inv_like_dt) == 0) return(NULL)
  il_chr <- inv_like_dt[chrom == chr]
  if (nrow(il_chr) == 0) return(NULL)

  # inv_like_dt may not have start_bp if generated by older C01a -- join if needed
  if (!"start_bp" %in% names(il_chr)) {
    dt <- precomp_list[[chr]]$dt
    if ("global_window_id" %in% names(dt) && "global_window_id" %in% names(il_chr)) {
      il_chr <- merge(il_chr, dt[, .(global_window_id, start_bp, end_bp)],
                       by = "global_window_id", all.x = TRUE)
    } else {
      return(NULL)
    }
  }

  il_chr <- il_chr[is.finite(start_bp) & is.finite(inv_likeness)]
  if (nrow(il_chr) == 0) return(NULL)

  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]
  il_chr[, status := fifelse(inv_likeness >= 0.5, "PASS",
                     fifelse(inv_likeness >= 0.25, "WEAK", "FAIL"))]

  chr_med <- median(il_chr$inv_likeness, na.rm = TRUE)
  chr_q75 <- quantile(il_chr$inv_likeness, 0.75, na.rm = TRUE)

  p <- ggplot(il_chr, aes(x = pos_mb, y = inv_likeness, color = status)) +
    geom_point(size = 0.4, alpha = 0.6) +
    scale_color_manual(values = PAL_INV) +
    geom_hline(yintercept = chr_med, linetype = "dashed", color = "gray40", linewidth = 0.3) +
    geom_hline(yintercept = chr_q75, linetype = "dotted", color = "gray20", linewidth = 0.3) +
    geom_hline(yintercept = 0.90, linetype = "solid", color = "red3", linewidth = 0.3, alpha = 0.5) +
    annotate("text", x = min(il_chr$pos_mb), y = chr_med + 0.02,
             label = paste0("median=", round(chr_med, 3)), size = 2.5, hjust = 0) +
    annotate("text", x = min(il_chr$pos_mb), y = chr_q75 + 0.02,
             label = paste0("q75=", round(chr_q75, 3)), size = 2.5, hjust = 0) +
    labs(x = paste0(chr, " (Mb)"), y = "Inv-likeness",
         title = paste0(chr, " -- Inversion-Likeness Score"),
         subtitle = paste0(nrow(il_chr), " windows | ",
                          sum(il_chr$status == "PASS"), " PASS, ",
                          sum(il_chr$status == "WEAK"), " WEAK, ",
                          sum(il_chr$status == "FAIL"), " FAIL"),
         caption = paste0("Components: PVE1_excess (0.25) + eigen_ratio (0.20) + trimodality (0.25) + het_contrast (0.30)\n",
                         "Seed gate at 0.90 (red line) | chr median (dashed) | q75 (dotted)")) +
    THEME_BASE
  p
}

# -- 03: Robust z-score profile --------------------------------------
build_z_profile <- function(chr) {
  dt <- precomp_list[[chr]]$dt
  if (!"max_abs_z" %in% names(dt)) return(NULL)

  pdt <- dt[, .(pos_mb = (start_bp + end_bp) / 2e6, z = abs(max_abs_z))]
  pdt <- pdt[is.finite(z)]

  pdt[, z_class := fifelse(z >= 5, "z>=5",
                   fifelse(z >= 4, "z>=4",
                   fifelse(z >= 3, "z>=3",
                   fifelse(z >= 2, "z>=2",
                   fifelse(z >= 1.5, "z>=1.5", "z<1.5")))))]

  p <- ggplot(pdt, aes(x = pos_mb, y = z, color = z_class)) +
    geom_point(size = 0.4, alpha = 0.6) +
    scale_color_manual(values = PAL_Z) +
    geom_hline(yintercept = 1.2, linetype = "dashed", color = "darkorange", linewidth = 0.3) +
    geom_hline(yintercept = 1.8, linetype = "dashed", color = "green4", linewidth = 0.3) +
    geom_hline(yintercept = 2.5, linetype = "dashed", color = "blue4", linewidth = 0.3) +
    labs(x = paste0(chr, " (Mb)"), y = "|Robust z|",
         title = paste0(chr, " -- Robust Z-Score Profile"),
         subtitle = paste0(nrow(pdt), " windows | z>=2.5: ", sum(pdt$z >= 2.5),
                          " | z>=1.8: ", sum(pdt$z >= 1.8),
                          " | z>=1.2: ", sum(pdt$z >= 1.2)),
         caption = "Thresholds: S1S=2.5 (blue) | S1M=1.8 (green) | S1L=1.2 (orange)") +
    THEME_BASE
  p
}

# -- 04: Background continuity baseline ------------------------------
build_bg_baseline <- function(chr) {
  pc <- precomp_list[[chr]]
  bg_q <- pc$bg_continuity_quantiles
  if (is.null(bg_q) || length(bg_q) < 4) return(NULL)

  # Ensure names are accessible (might be "50%" or just numeric indices)
  if (is.null(names(bg_q))) names(bg_q) <- paste0(c(50, 75, 80, 85, 90, 95), "%")[seq_along(bg_q)]

  # Adjacent-pair sim_mat values for histogram
  sim_mat <- pc$sim_mat
  n_w <- nrow(sim_mat)
  if (n_w < 5) return(NULL)
  adj_sims <- vapply(seq_len(n_w - 1), function(i) {
    s <- sim_mat[i, i + 1L]
    if (is.finite(s)) s else NA_real_
  }, numeric(1))
  adj_sims <- adj_sims[is.finite(adj_sims)]
  if (length(adj_sims) < 10) return(NULL)

  pdt <- data.table(sim = adj_sims)

  p <- ggplot(pdt, aes(x = sim)) +
    geom_histogram(bins = 80, fill = "lightblue", color = "blue4", linewidth = 0.2) +
    geom_vline(xintercept = as.numeric(bg_q["50%"]), color = "gray40", linetype = "dashed") +
    geom_vline(xintercept = as.numeric(bg_q["85%"]), color = "darkorange", linetype = "dashed") +
    geom_vline(xintercept = as.numeric(bg_q["90%"]), color = "green4", linetype = "dashed") +
    geom_vline(xintercept = as.numeric(bg_q["95%"]), color = "red3", linetype = "dashed") +
    annotate("text", x = as.numeric(bg_q["85%"]), y = Inf, vjust = 1.5,
             label = paste0("q85=", round(bg_q["85%"], 3)), size = 2.5, color = "darkorange") +
    annotate("text", x = as.numeric(bg_q["90%"]), y = Inf, vjust = 3,
             label = paste0("q90=", round(bg_q["90%"], 3)), size = 2.5, color = "green4") +
    annotate("text", x = as.numeric(bg_q["95%"]), y = Inf, vjust = 4.5,
             label = paste0("q95=", round(bg_q["95%"], 3)), size = 2.5, color = "red3") +
    labs(x = "Adjacent-window similarity", y = "Count",
         title = paste0(chr, " -- Background Continuity Baseline"),
         subtitle = paste0("From adjacent below-median-inv window pairs\n",
                          "Adaptive thresholds: S1S=q95 S1M=q90 S1L=q85"),
         caption = paste0("q50=", round(bg_q["50%"], 3),
                         " q75=", round(bg_q["75%"], 3),
                         " q85=", round(bg_q["85%"], 3),
                         " q90=", round(bg_q["90%"], 3),
                         " q95=", round(bg_q["95%"], 3))) +
    THEME_BASE
  p
}

# -- 05: NN distance profile (adaptive + smoothed regime bands) -------
build_nn_profile <- function(chr) {
  dt <- precomp_list[[chr]]$dt
  if (!"seed_nn_dist" %in% names(dt)) return(NULL)

  pdt <- dt[, .(pos_mb = (start_bp + end_bp) / 2e6, nn = seed_nn_dist)]
  pdt <- pdt[is.finite(nn)]
  if (nrow(pdt) < 30) return(NULL)

  # Adaptive quantiles
  qq <- quantile(pdt$nn, c(0.25, 0.50, 0.75), na.rm = TRUE)
  y_cap <- quantile(pdt$nn, 0.99, na.rm = TRUE) * 1.1  # cap y-axis at q99 + 10%

  # Smoothed NN for regime detection
  smooth_w <- min(31L, nrow(pdt) %/% 10L)
  if (smooth_w %% 2 == 0) smooth_w <- smooth_w + 1L
  smooth_w <- max(5L, smooth_w)
  pdt[, nn_smooth := frollmedian(nn, n = smooth_w, align = "center", na.rm = TRUE)]

  # Regime segmentation on smoothed track
  pdt[, nn_state := fifelse(nn_smooth <= qq["25%"], "core_low",
                   fifelse(nn_smooth <= qq["50%"], "mid", "background"))]
  pdt[, nn_state := nafill(nn_state, type = "locf")]
  pdt[is.na(nn_state), nn_state := "background"]
  pdt[, run_id := rleid(nn_state)]

  runs <- pdt[, .(state = first(nn_state), start_mb = min(pos_mb),
                   end_mb = max(pos_mb), n_win = .N), by = run_id]
  runs <- runs[n_win >= 10]  # drop tiny runs

  p <- ggplot(pdt, aes(x = pos_mb, y = nn)) +
    # Regime background bands
    {if (nrow(runs) > 0) geom_rect(
      data = runs, inherit.aes = FALSE,
      aes(xmin = start_mb, xmax = end_mb, ymin = -Inf, ymax = Inf, fill = state),
      alpha = 0.12
    )} +
    scale_fill_manual(values = c("core_low" = "blue3", "mid" = "darkseagreen3",
                                  "background" = "grey80"), name = "Regime") +
    # Raw points
    geom_point(size = 0.3, alpha = 0.35, color = "slateblue") +
    # Smoothed line
    geom_line(aes(y = nn_smooth), color = "black", linewidth = 0.5, na.rm = TRUE) +
    # Adaptive thresholds
    geom_hline(yintercept = qq["25%"], linetype = "dashed", color = "blue4", linewidth = 0.4) +
    geom_hline(yintercept = qq["50%"], linetype = "dashed", color = "green4", linewidth = 0.4) +
    geom_hline(yintercept = qq["75%"], linetype = "dashed", color = "darkorange", linewidth = 0.4) +
    labs(x = paste0(chr, " (Mb)"), y = "NN Distance (MDS-space)",
         title = paste0(chr, " -- Nearest-Neighbor Distance Along Chromosome"),
         subtitle = paste0(nrow(pdt), " windows (100-SNP, step-20) | ",
                          "Adaptive quantiles: q25=", round(qq["25%"], 3),
                          " q50=", round(qq["50%"], 3), " q75=", round(qq["75%"], 3)),
         caption = paste0("Source: MDS embedding of local PCA similarity matrix (chunked_2x, 20 dims)\n",
                         "Low NN = tightly clustered windows = consistent PCA signal (inversion core)\n",
                         "Blue band = core_low (<q25) | Green = mid (q25-q50) | Grey = background\n",
                         "Black line = rolling median (w=", smooth_w, ")")) +
    coord_cartesian(ylim = c(0, y_cap)) +
    THEME_BASE
  p
}

# -- 12: Combined 4-panel profile ------------------------------------
build_combined_profile <- function(chr) {
  dt <- precomp_list[[chr]]$dt
  n <- nrow(dt)
  pos_mb <- (dt$start_bp + dt$end_bp) / 2e6

  # Build panel data
  panels <- list()

  # Panel A: eigenvalue
  l1_col <- if ("lam_1" %in% names(dt)) "lam_1" else if ("lambda1" %in% names(dt)) "lambda1" else NULL
  l2_col <- if ("lam_2" %in% names(dt)) "lam_2" else if ("lambda2" %in% names(dt)) "lambda2" else NULL
  if (!is.null(l1_col) && !is.null(l2_col)) {
    pve1 <- dt[[l1_col]] / (dt[[l1_col]] + dt[[l2_col]])
    panels[["A_PVE1"]] <- data.table(pos_mb = pos_mb, value = pve1, panel = "A: PVE1")
  }

  # Panel B: z-score
  if ("max_abs_z" %in% names(dt)) {
    panels[["B_zscore"]] <- data.table(pos_mb = pos_mb, value = dt$max_abs_z,
                                        panel = "B: |z-score|")
  }

  # Panel C: inv-likeness
  if ("inv_likeness" %in% names(dt)) {
    panels[["C_inv"]] <- data.table(pos_mb = pos_mb, value = dt$inv_likeness,
                                     panel = "C: Inv-likeness")
  } else if (nrow(inv_like_dt) > 0) {
    il_chr <- merge(data.table(global_window_id = dt$global_window_id, pos_mb = pos_mb),
                     inv_like_dt[chrom == chr, .(global_window_id, inv_likeness)],
                     by = "global_window_id", all.x = TRUE)
    panels[["C_inv"]] <- data.table(pos_mb = il_chr$pos_mb, value = il_chr$inv_likeness,
                                     panel = "C: Inv-likeness")
  }

  # Panel D: NN distance
  if ("seed_nn_dist" %in% names(dt)) {
    panels[["D_nn"]] <- data.table(pos_mb = pos_mb, value = dt$seed_nn_dist,
                                    panel = "D: NN distance")
  }

  if (length(panels) < 2) return(NULL)

  pdt <- rbindlist(panels)
  pdt <- pdt[is.finite(value)]
  pdt[, panel := factor(panel, levels = c("A: PVE1", "B: |z-score|",
                                           "C: Inv-likeness", "D: NN distance"))]

  # Color by signal strength within each panel
  pdt[, value_q := frank(value, na.last = "keep") / .N, by = panel]

  p <- ggplot(pdt, aes(x = pos_mb, y = value, color = value_q)) +
    geom_point(size = 0.5, alpha = 0.6) +
    scale_color_gradientn(colours = c("grey80", "steelblue", "gold", "red3"),
                          name = "Quantile") +
    facet_wrap(~ panel, ncol = 1, scales = "free_y") +
    labs(x = paste0(chr, " (Mb)"), y = NULL,
         title = paste0(chr, " -- Combined Signal Profile"),
         subtitle = paste0(n, " windows -- red = high signal, grey = low"),
         caption = "Coincident red peaks across panels A+B+C with blue D = strong inversion") +
    THEME_BASE +
    theme(strip.text = element_text(face = "bold", size = 9),
          strip.background = element_rect(fill = "grey90", color = NA),
          panel.spacing = unit(0.8, "lines"))
  p
}


# -- 24: Local entropy profile along chromosome ----------------------
build_entropy_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0 || !"local_entropy" %in% names(il_chr)) return(NULL)
  il_chr <- il_chr[is.finite(local_entropy) & is.finite(start_bp)]
  if (nrow(il_chr) < 20) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  p <- ggplot(il_chr, aes(x = pos_mb)) +
    geom_point(aes(y = local_entropy), size = 0.4, alpha = 0.5, color = "darkorange") +
    geom_hline(yintercept = log(3), linetype = "dashed", color = "grey50", linewidth = 0.3) +
    labs(x = paste0(chr, " (Mb)"), y = "Local Shannon entropy (H)",
         title = paste0(chr, " -- Local Structure Entropy Profile"),
         subtitle = paste0(nrow(il_chr), " windows | chr-wide fixed k=3 bands, per-window soft membership"),
         caption = paste0("Source: per-window PC1 loadings measured against chromosome-wide fixed k=3 bands\n",
                         "Soft membership via inverse distance to fixed band means\n",
                         "H = -\u03A3 P_i \u00B7 ln(P_i) averaged across 226 samples\n",
                         "Low H = clean single group dominates | High H = mixed | Dashed = ln(3) = max for k=3")) +
    THEME_BASE
  p
}


# -- 25: ENA profile along chromosome --------------------------------
build_ena_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0 || !"local_ena" %in% names(il_chr)) return(NULL)
  il_chr <- il_chr[is.finite(local_ena) & is.finite(start_bp)]
  if (nrow(il_chr) < 20) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  p <- ggplot(il_chr, aes(x = pos_mb, y = local_ena)) +
    geom_point(size = 0.4, alpha = 0.5, color = "red3") +
    geom_hline(yintercept = 1, linetype = "dashed", color = "green4", linewidth = 0.3) +
    geom_hline(yintercept = 3, linetype = "dotted", color = "grey50", linewidth = 0.3) +
    labs(x = paste0(chr, " (Mb)"), y = "Effective Number of Backgrounds (ENA)",
         title = paste0(chr, " -- ENA Profile"),
         subtitle = paste0(nrow(il_chr), " windows | ENA = exp(H), chr-wide fixed bands"),
         caption = paste0("Source: exp(local Shannon entropy) from chr-wide fixed k=3 band memberships\n",
                         "ENA \u2248 1 = single clean background (green dashed)\n",
                         "ENA \u2248 3 = max mixing for k=3 (grey dotted)\n",
                         "No smoothing applied: raw per-window values")) +
    THEME_BASE
  p
}

# -- 27: Three-track decomposition profile (structure + inv + family) ──
build_three_track_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0) return(NULL)
  has_fam <- "family_likeness" %in% names(il_chr) && any(is.finite(il_chr$family_likeness))
  has_str <- "structure_likeness" %in% names(il_chr) && any(is.finite(il_chr$structure_likeness))
  if (!has_str) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  tracks <- list()
  tracks[["Structure"]] <- data.table(pos_mb = il_chr$pos_mb, value = il_chr$structure_likeness,
                                       track = "A: Structure-likeness (PVE1)")
  tracks[["Inversion"]] <- data.table(pos_mb = il_chr$pos_mb, value = il_chr$inv_likeness,
                                       track = "B: Inv-likeness (50% het + 25% PVE + 25% dip)")
  if (has_fam)
    tracks[["Family"]] <- data.table(pos_mb = il_chr$pos_mb, value = il_chr$family_likeness,
                                      track = "C: Family-likeness (Q variance by bands)")

  pdt <- rbindlist(tracks)
  pdt <- pdt[is.finite(value)]
  pdt[, track := factor(track, levels = unique(track))]

  p <- ggplot(pdt, aes(x = pos_mb, y = value)) +
    geom_point(size = 0.3, alpha = 0.4, color = "steelblue") +
    geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey50", linewidth = 0.3) +
    facet_wrap(~ track, ncol = 1, scales = "free_y") +
    labs(x = paste0(chr, " (Mb)"), y = "Score [0-1]",
         title = paste0(chr, " -- Three-Track Decomposition"),
         subtitle = paste0("A: captures all structure | B: inversion-specific | C: family-driven"),
         caption = paste0("Ideal inversion: A high + B high + C low\n",
                         "Family block: A high + B moderate + C high\n",
                         "Background: all low | Dashed = 0.5 threshold")) +
    THEME_BASE +
    theme(strip.text = element_text(face = "bold", size = 8),
          panel.spacing = unit(0.5, "lines"))
  p
}

# -- 28: Family-likeness profile ──
build_family_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0 || !"family_likeness" %in% names(il_chr)) return(NULL)
  il_chr <- il_chr[is.finite(family_likeness)]
  if (nrow(il_chr) < 20) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  p <- ggplot(il_chr, aes(x = pos_mb, y = family_likeness)) +
    geom_point(size = 0.4, alpha = 0.5, color = "purple3") +
    geom_hline(yintercept = 0.5, linetype = "dashed", color = "red3", linewidth = 0.3) +
    labs(x = paste0(chr, " (Mb)"), y = "Family-likeness",
         title = paste0(chr, " -- Family-Likeness Profile (Q-based)"),
         subtitle = paste0(nrow(il_chr), " windows | Fraction of Q variance explained by k=3 PC1 bands"),
         caption = paste0("Source: per-window ANOVA of NGSadmix Q components by k=3 band membership\n",
                         "High = bands recapitulate ancestry → family-driven grouping\n",
                         "Low = bands mix ancestry → structural signal (inversion)\n",
                         "Red dashed = 0.5 threshold | Requires --qmatrix in precomp")) +
    THEME_BASE
  p
}

# -- 29: Dosage het rate profile ──
build_dosage_het_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0) return(NULL)
  has_mean <- "dosage_het_rate_median" %in% names(il_chr) && any(is.finite(il_chr$dosage_het_rate_median))
  has_cv <- "dosage_het_rate_cv" %in% names(il_chr) && any(is.finite(il_chr$dosage_het_rate_cv))
  if (!has_mean && !has_cv) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  tracks <- list()
  if (has_mean) {
    tracks[["median"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$dosage_het_rate_median,
      track = "A: Median het rate (across 226 samples)")
  }
  if (has_cv) {
    tracks[["cv"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$dosage_het_rate_cv,
      track = "B: Het rate CV (bimodality signal)")
  }
  if ("dosage_het_rate_sd" %in% names(il_chr) && any(is.finite(il_chr$dosage_het_rate_sd))) {
    tracks[["sd"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$dosage_het_rate_sd,
      track = "C: Het rate SD")
  }

  pdt <- rbindlist(tracks)
  pdt <- pdt[is.finite(value)]
  pdt[, track := factor(track, levels = unique(track))]

  p <- ggplot(pdt, aes(x = pos_mb, y = value)) +
    geom_point(size = 0.3, alpha = 0.4, color = "darkgreen") +
    facet_wrap(~ track, ncol = 1, scales = "free_y") +
    labs(x = paste0(chr, " (Mb)"), y = NULL,
         title = paste0(chr, " -- Dosage Het Rate Profile (Independent from PCA)"),
         subtitle = "From raw dosage: fraction of sites with dosage in [0.3, 1.7] per sample",
         caption = paste0("Source: raw allele dosage matrix, NOT PC1 projection\n",
                         "A: MEDIAN het level (robust to outliers, higher in diverse regions)\n",
                         "B: CV = sd/median — HIGH CV = some samples very het, others hom = INVERSION SIGNAL\n",
                         "C: raw SD | Requires --dosage_dir in precomp")) +
    THEME_BASE +
    theme(strip.text = element_text(face = "bold", size = 8))
  p
}

# -- 30: Band fraction profile ──
build_band_fraction_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0 || !"band1_frac" %in% names(il_chr)) return(NULL)
  il_chr <- il_chr[is.finite(band1_frac)]
  if (nrow(il_chr) < 20) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  pdt <- melt(il_chr[, .(pos_mb, band1_frac, band2_frac, band3_frac)],
              id.vars = "pos_mb", variable.name = "band", value.name = "fraction")
  pdt[, band := factor(band, levels = c("band1_frac", "band2_frac", "band3_frac"),
                         labels = c("Band 1 (low PC1)", "Band 2 (mid/het)", "Band 3 (high PC1)"))]

  p <- ggplot(pdt[is.finite(fraction)], aes(x = pos_mb, y = fraction, color = band)) +
    geom_point(size = 0.3, alpha = 0.3) +
    scale_color_manual(values = c("Band 1 (low PC1)" = "#3b82f6",
                                    "Band 2 (mid/het)" = "#22c55e",
                                    "Band 3 (high PC1)" = "#ef4444")) +
    geom_hline(yintercept = 1/3, linetype = "dotted", color = "grey50") +
    labs(x = paste0(chr, " (Mb)"), y = "Fraction of samples",
         title = paste0(chr, " -- Band Fraction Profile (k=3 Fixed Bands)"),
         subtitle = "Fraction of 226 samples in each chromosome-wide k=3 band per window",
         caption = paste0("Source: per-window PC1 loadings assigned to nearest chr-wide k=3 center\n",
                         "Balanced bands (~33% each) = common inversion or strong structure\n",
                         "Unbalanced (one band dominates) = rare inversion or weak signal\n",
                         "Dotted = 1/3 (equal split)"),
         color = NULL) +
    THEME_BASE
  p
}

# -- 31: Local Q profile (from ancestry_bridge cache) ──
build_localQ_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0) return(NULL)
  has_lq <- "localQ_delta12" %in% names(il_chr) && any(is.finite(il_chr$localQ_delta12))
  if (!has_lq) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  tracks <- list()
  tracks[["d12"]] <- data.table(pos_mb = il_chr$pos_mb,
    value = il_chr$localQ_delta12, track = "A: Local Q \u039412 (dominance)")
  if ("localQ_entropy" %in% names(il_chr))
    tracks[["H"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$localQ_entropy, track = "B: Local Q entropy (H)")
  if ("localQ_ena" %in% names(il_chr))
    tracks[["ena"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$localQ_ena, track = "C: Local Q ENA")

  pdt <- rbindlist(tracks)
  pdt <- pdt[is.finite(value)]
  pdt[, track := factor(track, levels = unique(track))]

  p <- ggplot(pdt, aes(x = pos_mb, y = value)) +
    geom_point(size = 0.3, alpha = 0.4, color = "darkorange3") +
    facet_wrap(~ track, ncol = 1, scales = "free_y") +
    labs(x = paste0(chr, " (Mb)"), y = NULL,
         title = paste0(chr, " -- Local Q Profile (from ancestry_bridge)"),
         subtitle = "Real admixture proportions from fixed-F EM on BEAGLE GL (NOT PC1 proxy)",
         caption = paste0("Source: ancestry_bridge.R local Q projector (Skotte et al. 2013 math)\n",
                         "A: \u039412 = max(Q) - second(Q) per window, averaged across samples\n",
                         "B: Shannon entropy of local Q | C: ENA = exp(H)\n",
                         "These are INDEPENDENT from PCA — genuine admixture estimates")) +
    THEME_BASE +
    theme(strip.text = element_text(face = "bold", size = 8))
  p
}

# -- 32: PC1 het metrics profile (gap + mid_fraction + mid_variance) ──
build_het_metrics_profile <- function(chr) {
  il_chr <- if (nrow(inv_like_dt) > 0) inv_like_dt[chrom == chr] else data.table()
  if (nrow(il_chr) == 0) return(NULL)
  il_chr[, pos_mb := (start_bp + end_bp) / 2e6]

  tracks <- list()
  if ("het_pc1_gap" %in% names(il_chr) && any(is.finite(il_chr$het_pc1_gap)))
    tracks[["gap"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$het_pc1_gap, track = "A: PC1 gap (min dist between band centers)")
  if ("het_mid_fraction" %in% names(il_chr) && any(is.finite(il_chr$het_mid_fraction)))
    tracks[["mid"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$het_mid_fraction, track = "B: Middle band fraction (expected ~0.5 for inv)")
  if ("pc1_bimodality" %in% names(il_chr) && any(is.finite(il_chr$pc1_bimodality)))
    tracks[["bimod"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$pc1_bimodality, track = "C: PC1 bimodality (Ashman D)")
  if ("local_delta12" %in% names(il_chr) && any(is.finite(il_chr$local_delta12)))
    tracks[["d12"]] <- data.table(pos_mb = il_chr$pos_mb,
      value = il_chr$local_delta12, track = "D: \u039412 from fixed-band soft membership")

  if (length(tracks) < 2) return(NULL)
  pdt <- rbindlist(tracks)
  pdt <- pdt[is.finite(value)]
  pdt[, track := factor(track, levels = unique(track))]

  p <- ggplot(pdt, aes(x = pos_mb, y = value)) +
    geom_point(size = 0.3, alpha = 0.4, color = "steelblue") +
    facet_wrap(~ track, ncol = 1, scales = "free_y") +
    labs(x = paste0(chr, " (Mb)"), y = NULL,
         title = paste0(chr, " -- Het Metrics Profile (PC1-derived)"),
         subtitle = "Multiple het assessment channels from k=3 band analysis",
         caption = paste0("A: Min gap between k=3 centers — large gap = discrete groups\n",
                         "B: Fraction in middle band — ~0.50 for balanced common inversion\n",
                         "C: Ashman D between outer bands — high = bimodal = het signal\n",
                         "D: \u039412 from chr-wide fixed-band soft memberships\n",
                         "NOTE: all PC1-derived, not independent from eigenvalues")) +
    THEME_BASE +
    theme(strip.text = element_text(face = "bold", size = 7))
  p
}

# =============================================================================
# DISPATCH
# =============================================================================

plot_builders <- list(
  "01_eigenvalue_spectrum" = build_eigen_profile,
  "02_inv_likeness_profile" = build_inv_likeness_profile,
  "03_max_abs_z_profile" = build_z_profile,
  "04_bg_continuity_baseline" = build_bg_baseline,
  "05_nn_distance_profile" = build_nn_profile,
  "12_combined_profile" = build_combined_profile,
  "24_local_entropy_profile" = build_entropy_profile,
  "25_ena_profile" = build_ena_profile,
  "27_three_track_profile" = build_three_track_profile,
  "28_family_likeness_profile" = build_family_profile,
  "29_dosage_het_rate_profile" = build_dosage_het_profile,
  "30_band_fraction_profile" = build_band_fraction_profile,
  "31_local_Q_profile" = build_localQ_profile,
  "32_het_metrics_profile" = build_het_metrics_profile
)

plot_dims <- list(
  "01_eigenvalue_spectrum" = c(w = 14, h = 5),
  "02_inv_likeness_profile" = c(w = 14, h = 5),
  "03_max_abs_z_profile" = c(w = 14, h = 5),
  "04_bg_continuity_baseline" = c(w = 8, h = 5),
  "05_nn_distance_profile" = c(w = 14, h = 5),
  "12_combined_profile" = c(w = 16, h = 16),
  "24_local_entropy_profile" = c(w = 14, h = 5),
  "25_ena_profile" = c(w = 14, h = 5),
  "27_three_track_profile" = c(w = 14, h = 10),
  "28_family_likeness_profile" = c(w = 14, h = 5),
  "29_dosage_het_rate_profile" = c(w = 14, h = 10),
  "30_band_fraction_profile" = c(w = 14, h = 5),
  "31_local_Q_profile" = c(w = 14, h = 10),
  "32_het_metrics_profile" = c(w = 14, h = 12)
)

render_plots(plot_builders, plot_dims, chroms, precomp_list, cli$outdir)
message("[DONE] Profiles -> ", cli$outdir)
