#!/usr/bin/env bash
# =============================================================================
# 00_module3_config.sh — Configuration for heterozygosity + ROH/FROH module
# =============================================================================
# This module covers: per-sample het, local theta, ngsF-HMM ROH, FROH,
# summary tables, plots, stats, report.
# Breeding/scoring logic is a separate downstream module.
# =============================================================================
# Source from any pipeline script:
#   source "$(dirname "$0")/00_config.sh"
# =============================================================================

# ── Project root ────────────────────────────────────────────────────────────
PROJECT="${PROJECT:-/scratch/lt200308-agbsci/Quentin_project_KEEP_2026-02-04}"
BASE="${PROJECT}"

# ── Reference genome ────────────────────────────────────────────────────────
REF="${PROJECT}/00-samples/fClaHyb_Gar_LG.fa"
REF_FAI="${REF}.fai"

# ── Callable mask: TWO formats ─────────────────────────────────────────────
CALLABLE_BED="${PROJECT}/fClaHyb_Gar_LG.mask_regions.normalACGT.renamed.0based.bed"
CALLABLE_SITES="${PROJECT}/fClaHyb_Gar_LG.mask_regions.normalACGT.renamed.1-based.angsd"

# ── Repeat annotation ─────────────────────────────────────────────────────
REPEAT_BED="${PROJECT}/fClaHyb_Gar_LG.mask_regions.softacgt.bed"

# ── Sample manifest ─────────────────────────────────────────────────────────
SAMPLE_MANIFEST="${PROJECT}/pa_roary_results/00_manifests/sample_bam_minimap2_vs_P99TLENMAPQ30.tsv"

# ── BAM list (auto-generated by 01_prep) ───────────────────────────────────
BAMLIST_QCPASS="${PROJECT}/het_roh/01_inputs_check/bamlist_qcpass.txt"
SAMPLE_LIST="${PROJECT}/het_roh/01_inputs_check/samples_qcpass.txt"

# ── ngsF-HMM inputs ───────────────────────────────────────────────────────
BEAGLE_GL="${PROJECT}/het_roh/01_inputs_check/main_qcpass.beagle.gz"
POS_FILE="${PROJECT}/het_roh/01_inputs_check/main_qcpass.pos"
SAMPLES_IND="${PROJECT}/het_roh/01_inputs_check/samples.ind"

# ── ngsF-HMM executable + dependencies ────────────────────────────────────
NGSFHMM_BIN="/project/lt200308-agbsci/01-catfish_assembly/ngsF-HMM/ngsF-HMM"
NGSFHMM_WRAPPER="/project/lt200308-agbsci/01-catfish_assembly/ngsF-HMM/ngsF-HMM.sh"
NGSFHMM_MODULES=(
  "HTSlib/1.17-cpeGNU-23.03"
  "Boost/1.81.0-cpeGNU-23.03"
  "GSL/2.7-cpeGNU-23.03"
)

# ── Optional metadata ──────────────────────────────────────────────────────
NGSRELATE_PAIRS="${PROJECT}/popstruct_thin/05_ngsrelate/catfish_226_for_natora.txt"
PRUNED81_SAMPLES="${PROJECT}/popstruct_thin/05_ngsrelate/catfish_first_degree_pairwise_toKeep.txt"

# ── Ancestry / structure metadata ──────────────────────────────────────────
BESTK_TABLE="${PROJECT}/popstruct_thin/05_ngsadmix_global/best_seed_by_K.tsv"
NGSADMIX_DIR="${PROJECT}/popstruct_thin/05_ngsadmix_global/runs_thin500"
EVALADMIX_DIR="${PROJECT}/popstruct_thin/05_ngsadmix_global/evaladmix_thin500"
Q_MATRIX="${PROJECT}/popstruct_thin/05_ngsadmix_global/runs_thin500/thin500_K08_best.qopt"
COVTREE_ORDER="${PROJECT}/popstruct_thin/05_pcaangsd_global/thin_500/K4/catfish.wg.byRF.thin_500.pcangsd.tree"
ANCESTRY_LABELS="${PROJECT}/popstruct_thin/05_ngsadmix_global/sample_main_ancestry_by_K.tsv"

# ── Output base directory ──────────────────────────────────────────────────
OUTBASE="${PROJECT}/het_roh"

DIR_INPUTS="${OUTBASE}/01_inputs_check"
DIR_HET="${OUTBASE}/02_heterozygosity"
DIR_NGSFHMM="${OUTBASE}/03_ngsF_HMM"
DIR_ROH="${OUTBASE}/04_roh_summary"
DIR_INV="${OUTBASE}/05_inversion_support"
DIR_PLOTS_CORE="${OUTBASE}/06_plots_core"
DIR_PLOTS_META="${OUTBASE}/07_plots_metadata"
DIR_STATS="${OUTBASE}/08_stats"
DIR_TABLES="${OUTBASE}/09_final_tables"
DIR_REPORT="${OUTBASE}/10_report"
DIR_LOGS="${OUTBASE}/logs"

# ── Performance ─────────────────────────────────────────────────────────────
THREADS="${SLURM_CPUS_PER_TASK:-8}"

# ── ANGSD QC filters ───────────────────────────────────────────────────────
MINQ=20
MINMAPQ=30
CLIP=50

# ── realSFS convergence ───────────────────────────────────────────────────
REALSFS_MAXITER=2000
REALSFS_TOLE="1e-16"

# ── thetaStat windows (main scale) ───────────────────────────────────────
WIN=500000
STEP=500000

# ── Multiscale theta windows ─────────────────────────────────────────────
RUN_EXTRA_THETA_SCALES=1

THETA_SCALES=("5000_1000" "10000_2000" "50000_10000")
THETA_SCALE_LABELS=("5kb_1kb" "10kb_2kb" "50kb_10kb")

# ── ngsF-HMM settings ────────────────────────────────────────────────────
NGSFHMM_REPS=10
NGSFHMM_SEED_BASE=42

# =============================================================================
# Helper functions
# =============================================================================
hr_timestamp() { date '+%F %T'; }
hr_log() { echo "[$(hr_timestamp)] [HET-ROH] $*"; }
hr_err() { echo "[$(hr_timestamp)] [HET-ROH] [ERROR] $*" >&2; }
hr_die() { hr_err "$@"; exit 1; }

hr_check_file() {
  local f="$1" label="${2:-file}"
  [[ -e "$f" ]] || hr_die "Missing ${label}: ${f}"
}

hr_check_cmd() {
  command -v "$1" &>/dev/null || hr_die "Command not found: $1"
}

hr_init_dirs() {
  mkdir -p \
    "$DIR_INPUTS" "$DIR_HET" "$DIR_NGSFHMM" "$DIR_ROH" \
    "$DIR_INV" "$DIR_PLOTS_CORE" "$DIR_PLOTS_META" \
    "$DIR_STATS" "$DIR_TABLES" "$DIR_REPORT" "$DIR_LOGS" \
    "${DIR_HET}/01_saf" "${DIR_HET}/02_sfs" "${DIR_HET}/03_theta" \
    "${DIR_HET}/03_theta/multiscale" "${DIR_HET}/04_summary"
}
