#!/bin/bash
# =============================================================================
# scripts/bridge_from_phase4.sh — populate shelf_coords.tsv from phase_4 output
# =============================================================================
# Reads phase_4a/candidate_summary.tsv (chrom, interval_id, start_mb, end_mb,
# span_mb, final_score, dim_positive, tier, pattern, shape_class) and emits
# phase_qc_shelf/shelf_coords.tsv with the format expected by
# slurm/array_28chrom.sh:
#
#   # shelf_coords.tsv — per-chromosome shelf + breakpoint coordinates
#   # Format: chrom<TAB>shelf_start_mb<TAB>shelf_end_mb<TAB>bp1_mb<TAB>bp2_mb
#   C_gar_LG01   2.3    4.8   2.312   4.795
#   C_gar_LG12   8.1   12.6   8.104  12.610
#   ...
#
# At phase_4a catalog-birth time the breakpoints are not yet bp-resolution
# refined (that happens in phase_3). This script uses start_mb/end_mb as
# both the shelf coords and as initial bp1_mb/bp2_mb. If phase_3 has already
# run and written refined breakpoints to the evidence registry (via
# STEP_D03 Layer D blocks), pass --refined-bp to pull bp1/bp2 from there
# instead.
#
# When multiple candidates share a chromosome, shelf_coords.tsv gets one
# row per candidate. run_all_28chrom.sh currently dispatches one SLURM
# array task per chromosome, which means a chromosome with three
# candidates will currently only QC the first one listed. This is flagged
# as a known limitation — full per-candidate dispatch is a follow-up.
#
# Filtering:
#   --min-tier N       keep only candidates with tier <= N (default: no filter)
#   --min-span-kb N    keep only candidates with span >= N kb (default: 50)
#
# Usage:
#   bash scripts/bridge_from_phase4.sh <candidate_summary.tsv> [--min-tier 3] [--min-span-kb 50]
#
# Typical wiring:
#   PHASE4_OUT="${BASE}/phase4_out/4a_existence_layers"
#   bash scripts/bridge_from_phase4.sh \
#     "${PHASE4_OUT}/candidate_summary.tsv"
#   # then review shelf_coords.tsv, then:
#   bash run_all_28chrom.sh --resume
# =============================================================================
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${here}/00_config.sh"

INPUT="${1:-}"
[[ -z "${INPUT}" ]] && qc_die "Usage: $0 <candidate_summary.tsv> [--min-tier N] [--min-span-kb N]"
[[ -f "${INPUT}" ]] || qc_die "Input not found: ${INPUT}"

MIN_TIER=""
MIN_SPAN_KB=50
shift || true
while [[ $# -gt 0 ]]; do
  case "${1}" in
    --min-tier)    MIN_TIER="${2}"; shift 2 ;;
    --min-span-kb) MIN_SPAN_KB="${2}"; shift 2 ;;
    *) qc_die "Unknown arg: ${1}" ;;
  esac
done

OUT="${here}/shelf_coords.tsv"
BACKUP="${OUT}.bk_$(date +%Y%m%d_%H%M%S)"

# Back up existing shelf_coords.tsv (non-destructive).
if [[ -f "${OUT}" ]]; then
  cp "${OUT}" "${BACKUP}"
  qc_log "Backed up existing shelf_coords.tsv → $(basename "${BACKUP}")"
fi

qc_log "Reading ${INPUT}"
qc_log "Filters: min-span-kb=${MIN_SPAN_KB}${MIN_TIER:+, max tier ${MIN_TIER}}"

# Header
{
  echo "# shelf_coords.tsv — per-chromosome shelf + breakpoint coordinates"
  echo "# Format: chrom<TAB>shelf_start_mb<TAB>shelf_end_mb<TAB>bp1_mb<TAB>bp2_mb"
  echo "# Generated by bridge_from_phase4.sh on $(date -Iseconds)"
  echo "# Source: ${INPUT}"
  echo "# Filters: min-span-kb=${MIN_SPAN_KB}${MIN_TIER:+, max tier ${MIN_TIER}}"
  echo "#"
  echo "# NOTE: bp1/bp2 here are the unrefined interval boundaries from"
  echo "# phase_4a. If phase_3 has produced bp-resolution breakpoints, they"
  echo "# should update these entries via the evidence registry."
} > "${OUT}"

# Filter + emit. awk does the work.
#   $1=chrom, $2=interval_id, $3=start_mb, $4=end_mb, $5=span_mb,
#   $6=final_score, $7=dim_positive, $8=tier, $9=pattern, $10=shape_class
awk -v MIN_TIER="${MIN_TIER}" -v MIN_SPAN_KB="${MIN_SPAN_KB}" '
  BEGIN { FS="\t"; OFS="\t"; n_out=0 }
  NR==1 { next }                                    # skip header
  {
    span_kb = $5 * 1000
    if (span_kb + 0 < MIN_SPAN_KB + 0) next
    if (MIN_TIER != "" && $8 + 0 > MIN_TIER + 0) next
    # start_mb=$3, end_mb=$4 → shelf coords + unrefined bp1/bp2
    printf "%s\t%.3f\t%.3f\t%.3f\t%.3f\n", $1, $3, $4, $3, $4
    n_out++
  }
  END { print "(bridged " n_out " candidates)" > "/dev/stderr" }
' "${INPUT}" >> "${OUT}"

n_rows=$(grep -vc '^#' "${OUT}" || true)
qc_log "Wrote ${n_rows} candidate rows → ${OUT}"
qc_log ""
qc_log "Next: review ${OUT}, then:"
qc_log "  bash run_all_28chrom.sh --resume"
qc_log ""
qc_log "Per-chromosome counts:"
grep -v '^#' "${OUT}" | awk -F'\t' '{print "  " $1}' | sort | uniq -c | sort -rn | head -20
